-- DATA TYPE CONVERSION
-- IMPLICIT CONVERSION
SELECT * FROM movies;


-- INTEGER = INTEGER
SELECT * FROM movies
WHERE movie_id = 1;


-- INTEGER = STRING
SELECT * FROM movies
WHERE movie_id = '1';


-- EXPLICIT CONVERSION
SELECT * FROM movies
WHERE movie_id = INTEGER '1'


-- CAST FUNCTION
SELECT CAST('10' AS INTEGER);

SELECT CAST('10n' AS INTEGER);


SELECT CAST('2020-01-01' AS DATE),
CAST('01-MAY-2020' AS DATE);

SELECT DATE '2020-01-01';


SELECT CAST('true' AS BOOLEAN),
CAST('false' AS BOOLEAN),
CAST('T' AS BOOLEAN),
CAST('F' AS BOOLEAN),
CAST('0' AS BOOLEAN),
CAST('y' AS BOOLEAN);


SELECT CAST('14.7678' AS REAL),
CAST('14.7778' AS DOUBLE PRECISION);


-- :: OPERATOR
SELECT '10'::INTEGER,
'2020-01-01'::DATE,
'01-01-2020'::DATE;


SELECT '2020-02-20 10:30:26.467'::TIMESTAMP;

SELECT '2020-01-20 10:30:26.467'::TIMESTAMPTZ;

SELECT '10 minutes'::INTERVAL,
'4 hours'::INTERVAL,
'1 day'::INTERVAL,
'2 weeks'::INTERVAL,
'5 months'::INTERVAL;


-- IMPLICIT TO EXPLICIT CONVERSION
SELECT 20!;

SELECT 20! AS "Factorial";

SELECT CAST(20 AS BIGINT)! AS "Factorial";


SELECT ROUND(10, 4) AS "Round";

SELECT ROUND(CAST(10 AS NUMERIC), 4) AS "Round";


SELECT SUBSTR('123456', 2) AS "Sub String";

SELECT SUBSTR(CAST('123456' AS TEXT), 4) AS "Sub String";


-- TABLE DATA CONVERSION
CREATE TABLE rating(
	rating_id SERIAL PRIMARY KEY,
	rating VARCHAR(1) NOT NULL
);

INSERT INTO rating (rating)
VALUES
('a'),
('b'),
('c'),
('d');

SELECT * FROM rating;

INSERT INTO rating (rating)
VALUES 
(1),
(2),
(3),
(4);


SELECT rating_id,
CASE
	WHEN rating~E'^\\d+$' THEN
		CAST(rating AS INTEGER)
	ELSE
		0
	END AS rating
FROM rating;